#!/bin/bash
echo "🔐 Granting Admin Consent for Microsoft OAuth"
echo ""
echo "Opening admin consent URL..."
echo ""
echo "URL: https://login.microsoftonline.com/common/adminconsent?client_id=dd0f2824-3ec3-4b80-90a3-a9fcd34be3ed"
echo ""
echo "Steps:"
echo "1. Make sure you're logged into Azure Portal with admin account"
echo "2. The URL will open in your browser"
echo "3. Click 'Accept' to grant admin consent"
echo "4. Wait 2-3 minutes for changes to propagate"
echo "5. Try logging in with company account again"
echo ""
read -p "Press Enter to open the URL in your browser..."
open "https://login.microsoftonline.com/common/adminconsent?client_id=dd0f2824-3ec3-4b80-90a3-a9fcd34be3ed" 2>/dev/null || echo "Please open this URL manually: https://login.microsoftonline.com/common/adminconsent?client_id=dd0f2824-3ec3-4b80-90a3-a9fcd34be3ed"
