"""add policy tables

Revision ID: 0b34eb58d39a
Revises: 3c60e1187947
Create Date: 2026-01-03 02:29:26.779801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0b34eb58d39a'
down_revision: Union[str, None] = '4f95b897a5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('policy_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('intent_summary', sa.Text(), nullable=True),
    sa.Column('tool_call_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_session_id'), 'policy_decisions', ['session_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_user_id'), 'policy_decisions', ['user_id'], unique=False)
    
    op.create_table('pending_confirmations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('tool_args', sa.JSON(), nullable=False),
    sa.Column('required_phrase', sa.String(), nullable=True),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_confirmations_session_id'), 'pending_confirmations', ['session_id'], unique=False)
    op.create_index(op.f('ix_pending_confirmations_user_id'), 'pending_confirmations', ['user_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_confirmations_user_id'), table_name='pending_confirmations')
    op.drop_index(op.f('ix_pending_confirmations_session_id'), table_name='pending_confirmations')
    op.drop_table('pending_confirmations')
    op.drop_index(op.f('ix_policy_decisions_user_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_session_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
