"""add_core_tables_pgvector

Revision ID: 3c60e1187947
Revises: 4f95b897a5b8
Create Date: 2026-01-02 23:43:34.647688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.db.types


# revision identifiers, used by Alembic.
revision: str = '3c60e1187947'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', src.db.types.UUIDType(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('microsoft_access_token', sa.String(), nullable=True),
    sa.Column('microsoft_refresh_token', sa.String(), nullable=True),
    sa.Column('microsoft_token_expires_at', src.db.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('created_at', src.db.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', src.db.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', src.db.types.TZDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('memories',
    sa.Column('id', src.db.types.UUIDType(length=36), nullable=False),
    sa.Column('user_id', src.db.types.UUIDType(length=36), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    # sa.Column('embedding', pgvector.sqlalchemy.Vector(1536), nullable=False), # PGVECTOR NOT INSTALLED
    sa.Column('metadata', src.db.types.JsonBType(), server_default='{}', nullable=False),
    sa.Column('created_at', src.db.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', src.db.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('decay_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('ix_memories_embedding_hnsw', 'memories', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_memories_user_id_created_at', 'memories', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_memories_user_id_type', 'memories', ['user_id', 'type'], unique=False)
    op.create_table('sessions',
    sa.Column('id', src.db.types.UUIDType(length=36), nullable=False),
    sa.Column('user_id', src.db.types.UUIDType(length=36), nullable=False),
    sa.Column('started_at', src.db.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', src.db.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('metadata', src.db.types.JsonBType(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_user_id_started_at', 'sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', src.db.types.UUIDType(length=36), nullable=False),
    sa.Column('session_id', src.db.types.UUIDType(length=36), nullable=False),
    sa.Column('user_id', src.db.types.UUIDType(length=36), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('modality', sa.String(), nullable=False),
    sa.Column('created_at', src.db.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_session_id_created_at', 'messages', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_messages_user_id_created_at', 'messages', ['user_id', 'created_at'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', src.db.types.UUIDType(length=36), nullable=False),
    sa.Column('session_id', src.db.types.UUIDType(length=36), nullable=False),
    sa.Column('user_id', src.db.types.UUIDType(length=36), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('args', src.db.types.JsonBType(), server_default='{}', nullable=False),
    sa.Column('result', src.db.types.JsonBType(), server_default='{}', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', src.db.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tool_calls_session_id_created_at', 'tool_calls', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_tool_calls_tool_name_created_at', 'tool_calls', ['tool_name', 'created_at'], unique=False)
    op.create_index('ix_tool_calls_user_id_created_at', 'tool_calls', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_calls_user_id_created_at', table_name='tool_calls')
    op.drop_index('ix_tool_calls_tool_name_created_at', table_name='tool_calls')
    op.drop_index('ix_tool_calls_session_id_created_at', table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index('ix_messages_user_id_created_at', table_name='messages')
    op.drop_index('ix_messages_session_id_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_sessions_user_id_started_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_memories_user_id_type', table_name='memories')
    op.drop_index('ix_memories_user_id_created_at', table_name='memories')
    op.drop_index('ix_memories_embedding_hnsw', table_name='memories', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('memories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_email', table_name='users', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_table('users')
    # ### end Alembic commands ###

