"""add_password_reset_tokens

Revision ID: 4f95b897a5b8
Revises: ec4f65823ae4
Create Date: 2026-01-01 19:49:06.914507

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '4f95b897a5b8'
down_revision: Union[str, None] = 'ec4f65823ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

